In [5]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt 
import random

In [8]:
from dataclasses import dataclass

In [10]:
@dataclass
class Config:
    x: int = 2

In [11]:
Config.x + 2

4

In [14]:
names = ['apple', 'banana', 'cherry']
chars = sorted(list(set(''.join(names))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [15]:
names

['apple', 'banana', 'cherry']

In [16]:
encode = lambda s: [stoi[c] for c in s] 
decode = lambda l: ''.join([itos[i] for i in l])

In [27]:
data = []
for w in names:
    data = data + ([0]*3) + encode(w)
data

[0, 0, 0, 1, 8, 8, 6, 4, 0, 0, 0, 2, 1, 7, 1, 7, 1, 0, 0, 0, 3, 5, 4, 9, 9, 10]

In [55]:
name = torch.zeros(1,8)
name.shape

torch.Size([1, 8])

In [56]:
a = 3
name = torch.cat((name, torch.tensor([a]).view(1,1)), dim=1)
name

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 3.]])

In [52]:
name = torch.cat((name, a),dim=1)
name.shape

torch.Size([1, 9])

In [57]:
name[:,-8:]
name

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 3.]])

In [58]:
x = torch.ones(10)
y = torch.zeros(10)
data = {'t': x, 'v': y}
for k in ['t', 'v']:
    print(data[k])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [59]:
import torch.nn as nn
class Test(nn.Module):
    def __init__(self):
        super().__init__()
    self.d = nn.ModuleDict(dict(
        

_IncompleteInputError: incomplete input (1168599645.py, line 3)